# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import course_info_pb2 as course__info__pb2


class CourseInfoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCourseInfo = channel.unary_unary(
                '/CourseInfo/GetCourseInfo',
                request_serializer=course__info__pb2.CourseInfoRequest.SerializeToString,
                response_deserializer=course__info__pb2.CourseInfoReply.FromString,
                )


class CourseInfoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCourseInfo(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CourseInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCourseInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCourseInfo,
                    request_deserializer=course__info__pb2.CourseInfoRequest.FromString,
                    response_serializer=course__info__pb2.CourseInfoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CourseInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CourseInfo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCourseInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CourseInfo/GetCourseInfo',
            course__info__pb2.CourseInfoRequest.SerializeToString,
            course__info__pb2.CourseInfoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
